apiVersion: batch/v1
kind: Job
metadata:
  name: zhihu-discovery003
spec:
  template:
    spec:
      containers:
      - name: pi
        image: ccr.ccs.tencentyun.com/caryguo/discovery:0.3
      restartPolicy: Never
  backoffLimit: 4
