apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    k8s-app: mysql
  name: mysql-002
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mysql
  serviceName: mysql
  template:
    metadata:
      annotations:
        eks.tke.cloud.tencent.com/cpu: "1"
        eks.tke.cloud.tencent.com/mem: 2Gi
      labels:
        k8s-app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql
        imagePullPolicy: Always
        name: mysql
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        - name: timezone
          mountPath: /etc/localtime
          subPath: Shanghai
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: timezone-configmap                  #引用configMap卷
        configMap:
          name: timezone
          items:
            - key: Shanghai            #创建configMap指定的名称
              path: Shanghai          #里面的那个文件--from-file参数后面的文件
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: cbs


