apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-pdndsnrn
  name: mysql
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    k8s-app: mysql
  type: ClusterIP
